### ISSUE TITLE
What are core elements that most open science projects will tend to need or want?

### ISSUE THREAD

**Issue by dwhly** [OpenScienceRoadmap/mozilla-sprint-2018#10]
[//]: # "=======================
Instructions for posting issues: 
(1) Review what is already there. Perhaps a comment to an existing issue would be more appropriate than opening a new one?  Issues can be a topic idea, a cry for help, an introduction to yourself, a to-do, or a discussion / question about the event itself.
(2) Write your post (below this text blob) using Markdown (as per https://guides.github.com/features/mastering-markdown/ ) or just plain text.
(3) Don't worry about these introductory lines - you can leave or delete them, as they won't display anyway (you can check this via Preview).
(4) Hit the 'Submit new issue' button.
============================"

There are things that many science projects, experiments or other collaborations might tend to want or need.  We should categorize those and provide leading examples of known solutions in those categories.  It's possible there are already good inputs / catalogs that already exist.  What are they?

Potential categories might include:

Project management
Collaboration
Issue tracking
Code and data repositories
Manuscript authoring
Publishing
Peer review
Data analysis / Machine learning
Image processing

What are your suggestions?

**Comment by Daniel-Mietchen** [comment]
I guess this one is better discussed over at https://ask-open-science.org/ .

**Comment by Daniel-Mietchen** [comment]
Some categories of things that may be worth adding to your list above:
- interfaces with non-open infrastructure and/ or workflows, or components thereof
- community management
- usage stats

Perhaps we should set up a file where we can flesh this out?

**Comment by Daniel-Mietchen** [comment]
Logos are needed too. Besides our own ticket (#14), there is for instance https://github.com/OpenStories/website/issues/3 for another Mozsprint project.

**Comment by xolotl** [comment]
This issue was moved to OpenScienceRoadmap/roadmap#9
