### ISSUE TITLE
Could we set a calendar with the set/possible dates for the future sprint(s)? 

### ISSUE THREAD

**Issue by jbpoline** [OpenScienceRoadmap/mozilla-sprint-2018#12]
[//]: # "=======================
Instructions for posting issues: 
(1) Review what is already there. Perhaps a comment to an existing issue would be more appropriate than opening a new one?  Issues can be a topic idea, a cry for help, an introduction to yourself, a to-do, or a discussion / question about the event itself.
(2) Write your post (below this text blob) using Markdown (as per https://guides.github.com/features/mastering-markdown/ ) or just plain text.
(3) Don't worry about these introductory lines - you can leave or delete them, as they won't display anyway (you can check this via Preview).
(4) Hit the 'Submit new issue' button.
============================"

**Comment by dwhly** [comment]
There is a workshop being planned for this fall, towards the end of August, but other than that no other sprints are planned at the moment.  (Is that what you meant?)

**Comment by jbpoline** [comment]
Thanks, Yes, I thought it would be good to list the dates of these events in the front page, especially if they are open for registration - but even if they are not.

**Comment by emdupre** [comment]
It looks like the google group would be a great place to go for updates ! https://groups.google.com/forum/#!topic/jrost/ubwpQUt_3C0

**Comment by xolotl** [comment]
Yes, the google group would be the best place for email updates. OTOH, the community is welcome to organize additional collaboration at any time ;)

**Comment by xolotl** [comment]
This issue was moved to OpenScienceRoadmap/jrost#37
