### ISSUE TITLE
Things we learned through the 2018 Mozsprint

### ISSUE THREAD

**Issue by Daniel-Mietchen** [OpenScienceRoadmap/mozilla-sprint-2018#15]
Whenever you learn something during the course of this event, make a note in this thread.

For instance, by digging into [Endangered Data Week #153](https://github.com/mozilla/global-sprint/issues/153), I learned about 
- the [all-contributors](https://github.com/kentcdodds/all-contributors) project, which seeks to address &mdash;  at least for GitHub repos &mdash; the generic need of open projects to acknowledge diverse contributions. You can see it in action in the README of https://github.com/endangereddataweek/resources .
- a possibility to welcome newcomers to a project by having a "hello world" kind of ticket, which they have as their [issue 21](https://github.com/endangereddataweek/resources/issues/21). 

In both cases, we should probably set up something similar here.

This ticket was inspired by 
https://github.com/sparcopen/open-research-doathon/issues/45
and
https://github.com/sparcopen/open-research-doathon/issues/16 .

**Comment by Daniel-Mietchen** [comment]
In contrast to 12 other Wikipedias the English one does not have an entry on the number 808: https://www.wikidata.org/wiki/Q1492286#sitelinks-wikipedia .

**Comment by Daniel-Mietchen** [comment]
The digital preservation platform http://wikidp.org/ has shortlinks to information about individual items, e.g. for the image processing software ImageJ http://wikidp.org/Q1659584 .

**Comment by xolotl** [comment]
This issue was moved to OpenScienceRoadmap/jrost#38
