### ISSUE TITLE
Mapping the open science landscape: Let's get to know each other a bit by posting an intro here

### ISSUE THREAD

**Issue by Daniel-Mietchen** [OpenScienceRoadmap/mozilla-sprint-2018#16]
Perhaps following a structure like this (replicated at the bottom of this post for reuse):

- **Name**: Daniel Mietchen
- **ORCID** (use full URL): http://orcid.org/0000-0001-9488-1870
- **Your Mozsprint project/ submission**: https://github.com/mozilla/global-sprint/issues/285
- **What brought you here**: I am interested in integrating collaborative research workflows with the open web, and so are others, which is why we started thinking about a Joint Roadmap for Open Science Tools and submitted this Mozsprint project in order to exchange thoughts and ideas on this with you and others.
- **What you can imagine bringing or doing here**: Ideas and practical experience around ways in which different components of the open science landscape could be improved collectively. Hope to be able to move forward with some of these.
- **Contact outside GitHub**: e.g. https://twitter.com/EvoMRI or https://www.wikidata.org/wiki/Special:EmailUser/Daniel_Mietchen .
- **Anything else**: While this repo and almost all of my research-related writing is in English, I am also interested in how we can facilitate open-science interactions across languages.

All fields are optional.

This ticket was inspired by https://github.com/endangereddataweek/resources/issues/21 and anticipated in https://github.com/OpenScienceRoadmap/mozilla-sprint-2018/issues/15 .

<pre>
- **Name**: 
- **ORCID** (use full URL): 
- **Your Mozsprint project/ submission**: 
- **What brought you here**: 
- **What you can imagine bringing or doing here**: 
- **Contact outside GitHub**: 
- **Anything else**: 
</pre>

**Comment by HeidiSeibold** [comment]
- **Name**: Heidi Seibold
- **ORCID** (use full URL): http://orcid.org/0000-0002-8960-9642
- **Your Mozsprint project/ submission**: I'd like to help out here :woman_scientist: 
- **What brought you here**: I am an Open Science enthusiast. I am involved in **OpenML**, **Journal of Statistical Software** (OA journal, free for both authors and readers), **School of Data**, **R**. I am an Open Science Trainer (just joined the FOSTER bootcamp), am very much into automation and reproducibility of statistical analyses. I was part of the **Mozilla Open Leaders** last year.  
- **What you can imagine bringing or doing here**: I have experience in organising open projects and am involved in at least two projects that I believe fit in the Open Science lifecycle.
- **Contact outside GitHub**: https://twitter.com/HeidiBaya, http://www.ibe.med.uni-muenchen.de/mitarbeiter/mitarbeiter/seibold/index.html
- **Anything else**: :cat: :clap: :tada: :woman_scientist: :microscope: :raising_hand_woman:

**Comment by TomDemeranville** [comment]
- **Name**: Tom Demeranville 
- **ORCID** (use full URL): https://orcid.org/0000-0003-0902-4386
- **Your Mozsprint project/ submission**: Wherever I'm needed!
- **What brought you here**: I'm really keen to see open science tools reach their full potential
- **What you can imagine bringing or doing here**: I've not got anything specific, but I'm based at ORCID (I'm the Tech Advocate) so can help out with anything ORCID related. Feel free to get in touch!
- **Contact outside GitHub**: @tomdemeranville

**Comment by bmkramer** [comment]
- **Name**: Bianca Kramer
- **ORCID** (use full URL): https://orcid.org/0000-0002-5965-6560
- **Your Mozsprint project/ submission**: none specifically for this year's sprint, but previously: https://github.com/bmkramer/101innovations-survey-data
- **What brought you here**: Very happy to see this initiative to mapping open science tools and platforms, as it closely aligns with my own interest and ongoing activities (e.g. https://101innovations.wordpress.com)
- **What you can imagine bringing or doing here**: Prior collection of [tools & platforms and their usage in workflows](https://101innovations.wordpress.com/outcomes/), thinking on [principles / criteria](https://github.com/OpenScienceRoadmap/mozilla-sprint-2018/issues/13)
- **Contact outside GitHub**: https://twitter.com/MsPhelps 
- **Anything else**:

**Comment by dwhly** [comment]
- **Name**: Dan Whaley
- **ORCID** (use full URL): https://orcid.org/0000-0002-6532-2647
- **Your Mozsprint project/ submission**: https://github.com/mozilla/global-sprint/issues/285
- **What brought you here**: It's been increasingly clear that our project, Hypothes.is, and the broader paradigm of open Web Annotation (w3.org/annotation) fits within a broader landscape of open scholarly, and open scientific projects.  Our goal is to reach out and form deeper relationships with those projects, so that we can identify areas of mutual synergy and cooperation.  We notice that other open projects are more willing to collaborate in the fullest and truest sense, with nothing other than the delight and empowerment of researchers and other end users in mind.
- **What you can imagine bringing or doing here**: I want to begin sketching the outlines of the ecosystem, and to begin understanding the opportunities for integrations, interoperability and improved researcher potential.
- **Contact outside GitHub**: https://twitter.com/dwhly, https://hypothes.is/users/dwhly
- **Anything else**: Let's get started!

**Comment by hepplerj** [comment]
- **Name**: Jason Heppler
- **ORCID** (use full URL):  https://orcid.org/0000-0003-4158-6186
- **Your Mozsprint project/ submission**: [Endangered Data Week](https://github.com/endangereddataweek/resources)
- **What brought you here**: An introduction from [Daniel](https://github.com/endangereddataweek/resources/issues/21#issuecomment-387920014)!
- **What you can imagine bringing or doing here**: I think open science initiatives align very well with the kind of work we're doing with EDW. I'm eager to find ways we can work together, find overlap, and learn from each other. 
- **Contact outside GitHub**: https://jasonheppler.org, [@jaheppler](twitter.com/jaheppler)
- **Anything else**: Keep the coffee stocked!

**Comment by felliott** [comment]
- **Name**: Fitz Elliott
- **ORCID** (use full URL): - 
- **Your Mozsprint project/ submission**: Here to contribute however I can!
- **What brought you here**: I'm a developer at the [Center for Open Science](https://cos.io).  
- **What you can imagine bringing or doing here**: I'll be taking a stab at visualizing the open science toolspace, starting with the services that the OSF interacts with.
- **Contact outside GitHub**: fitz@cos.io
- **Anything else**: Go Science!

**Comment by nicipfeiffer** [comment]
**Name:** Nici Pfeiffer
**Your Mozsprint project/ submission**: None just yet...
**What brought you here:** As a Product Manager at the [Center for Open Science](https://cos.io/), I am interested in collaborating with other open science tools to support open research workflows for users of OSF and the collaborative landscape.  
**What you can imagine bringing or doing here**: I want to dive into those user stories and provide them to the JROST community to uncover opportunities and gaps to support a concrete roadmap, inevitably make science more open!
**Contact outside GitHub**: nici@cos.io

**Comment by xolotl** [comment]
- **Name**: Nate Angell
- **ORCID** (use full URL): [https://orcid.org/0000-0002-5224-3384](https://orcid.org/0000-0002-5224-3384)
- **Your Mozsprint project/ submission**: [Open Science Roadmap](https://github.com/mozilla/global-sprint/issues/285)
- **What brought you here**: I lead communications and marketing for [Hypothesis](https://web.hypothes.is), the nonprofit organization that develops and stewards open annotation technologies and practices.
- **What you can imagine bringing or doing here**: I'm hoping to make sure other contributors feel welcome and empowered to engage in the sprint, and beyond. I'd also like to contribute to building blocks for a mapping of the #openscience tool ecosystem, including personas, user stories, and data and visualizations of projects/tools and how they work together to make science possible/better.
- **Contact outside GitHub**: [@xolotl](https://twitter.com/xolotl) on Twitter
- **Anything else**: I live in Portland, Oregon USA and there's more info about my interests and activities on my [personal blog/website](http://xolotl.org).

**Comment by icereval** [comment]
- **Name**: Michael Haselton
- **ORCID** (use full URL): https://orcid.org/0000-0002-3816-0523
- **Your Mozsprint project/ submission**: Working with @felliott on one
- **What brought you here**: Engineering Manager at [Center for Open Science](https://cos.io)
- **What you can imagine bringing or doing here**: Visualize the open science ecosystem.
- **Contact outside GitHub**: [@icereval](http://twitter.com/icereval)

**Comment by bluerasberry** [comment]
- **Name**: Lane Rasberry
- **ORCID** (use full URL): https://orcid.org/0000-0002-9485-6146
- **Your Mozsprint project/ submission**: 
- **What brought you here**: I was checking out Mozilla projects with a Wikimedia component
- **What you can imagine bringing or doing here**: Wikimedia support
- **Contact outside GitHub**: user:bluerasberry in Wikimedia projects
- **Anything else**:

**Comment by Daniel-Mietchen** [comment]
@icereval @xolotl probably worth checking your ORCID settings to make sure your information there is actually public.

**Comment by xolotl** [comment]
@Daniel-Mietchen Actually as ORCID was invented after I stepped away from being a scholar, I've never updated it with any info. I put some things in there now so it's not so empty ;)

**Comment by xolotl** [comment]
This issue was moved to OpenScienceRoadmap/jrost#32
