### ISSUE TITLE
Review open science projects from other sprints, and engage

### ISSUE THREAD

**Issue by Daniel-Mietchen** [OpenScienceRoadmap/mozilla-sprint-2018#2]
For instance, 
- the [OpenCon 2017 Doathon](http://doathon.opencon2017.org/) had a flurry of [submissions](https://github.com/sparcopen/doathon/issues?q=is%3Aissue+is%3Aopen+sort%3Acomments-desc) relevant to our perspective on the open science landscape, 
- the [Open Science Barcamp this March](http://www.open-science-conference.eu/barcamp/) had a good number of [interesting sessions](https://etherpad.wikimedia.org/p/oscibar2018), and 
- there are hackathons, doathons, sprints and similar activities taking place around the globe on a daily basis, thereby contributing to the development of the open science landscape and related spaces.

It would be useful to review such activities systematically, to engage with them and to include them into the roadmap we are aiming to create.

**Comment by xolotl** [comment]
This issue was moved to OpenScienceRoadmap/jrost#35
