### ISSUE TITLE
Augment JROST Communications & Information Infrastructure

### ISSUE THREAD

**Issue by xolotl** [OpenScienceRoadmap/mozilla-sprint-2018#21]
JROST is a new project and as such has communication and information needs to help the project coordinate not just during this sprint, but on an ongoing basis. While JROST already has a domain (jrost.org), a generic [email address](info@jrost.org), a [basic website](http://jrost.org/), and a [basic wordmark](https://commons.wikimedia.org/wiki/File:JROST_Logo_(black_on_white).svg), additional needs include:
- [x] Clear licensing policies and practices
- [ ] Clear contributor policies and practices
- [x] A code of conduct
- [x] Augmentations to [the website](http://jrost.org)
- [x] A blog
- [ ] A better logo and/or wordmark
- [x] Transparent processes for individuals and organizations to join JROST
- [x] A channel for email communication
- [x] A channel for chat communication
- [x] Channels for social media communication
- [ ] Probably other things, suggestions welcome!

**Comment by xolotl** [comment]
JROST has adopted the [code of conduct](https://github.com/OpenScienceRoadmap/mozilla-sprint-2018/blob/master/CODE_OF_CONDUCT.md) established for our participation in the 2018 Mozilla Global Sprint.

**Comment by xolotl** [comment]
JROST published its [first blog post](http://jrost.org/2018/05/11/jrost-launched.html) during the 2018 #mozsprint.

**Comment by xolotl** [comment]
Work on a separate issue to improve processes for individuals and organizations to join JROST formally (#9) has resulted in a new [Participants repository](https://github.com/OpenScienceRoadmap/Participants/blob/master/JROSTOrganizations.csv) with instructions.

**Comment by xolotl** [comment]
You can now subscribe to the [JROST Google Group](https://groups.google.com/forum/#!forum/jrost) to receive and post emails to the community.

**Comment by xolotl** [comment]
During the 2018 #mozsprint, participants have been chatting on the #opensciroadmap IRC channel on freenode, via Twitter, and in a Zoom call that will only persist during the sprint. None of these chat channels seem optimal to me. It would be great to establish a chat mechanism with the following characteristics, but maybe such a thing is a mythical unicorn:
* easy to find and use
* open source
* non-commercial
* inexpensive
* easy to maintain
* persistent
* maintains history

Suggestions welcome!

**Comment by xolotl** [comment]
Twitter seems to be the most widely used social media channel among JROST participants, so for now, we have established the [@OpenSciRoadmap](https://twitter.com/OpenSciRoadmap) Twitter handle.

**Comment by HeidiSeibold** [comment]
If I search for JROST on twitter I don't find the right account. Maybe add JROST to the profile description? 

https://twitter.com/search?f=users&vertical=default&q=jrost&src=typd

**Comment by xolotl** [comment]
Added Slack join info to website: https://jrost.org/join#slack

**Comment by xolotl** [comment]
This issue was moved to OpenScienceRoadmap/jrost#31
