### ISSUE TITLE
Build a bibliography of open science

### ISSUE THREAD

**Issue by Daniel-Mietchen** [OpenScienceRoadmap/mozilla-sprint-2018#23]
A very basic version sits at https://tools.wmflabs.org/scholia/topic/Q309823 , biased towards publications I am aware of.

**Comment by Daniel-Mietchen** [comment]
Another starting point is the list at https://opensciencemooc.eu/open-science-resources/#one .

**Comment by zuphilip** [comment]
See also https://www.zotero.org/groups/415096/open_science_bibliography and possibly other Zotero groups.

**Comment by Daniel-Mietchen** [comment]
Tahnks, @zuphilip . Can you help bring these over to Wikidata?

**Comment by xolotl** [comment]
This issue was moved to OpenScienceRoadmap/roadmap#10
