### ISSUE TITLE
Curate Wikidata entries about components of the open science ecosystem

### ISSUE THREAD

**Issue by Daniel-Mietchen** [OpenScienceRoadmap/mozilla-sprint-2018#7]
Some guidance is available at
https://www.wikidata.org/wiki/Wikidata:WikiProject_Open .

The focus here is on improving existing items. If you're not sure whether something you're interested in has or, or should have one, please leave a comment here or on the Discussion page of the above WikiProject.

**Comment by Daniel-Mietchen** [comment]
There is a dedicated Mozsprint project for mapping the open ecosystem (so not limited to science) via Wikidata: https://github.com/mozilla/global-sprint/issues/237 .

**Comment by HeidiSeibold** [comment]
How do I make the connection to open science? Can I say "part of" "Open Science"? I am quite new to wikidata...

**Comment by HeidiSeibold** [comment]
I created entries for [open science movement](https://www.wikidata.org/wiki/Q52989815) and [open science tool](https://www.wikidata.org/wiki/Q52990223). Maybe this will help :nerd_face:

**Comment by Daniel-Mietchen** [comment]
Thanks, @HeidiSeibold . I added a bit to these items. For pieces of software and file formats known to Wikidata, 
http://wikidp.org/
provides a nice overview, e.g. see
http://wikidp.org/Q52988856 for OpenML and the discussion at
https://github.com/bioSyntax/bioSyntax/issues/1 (pinging @emulatingkat ).

Yes, the graph builder and the Wikidata SPARQL endpoint could be used for some visualizations, so it would make sense to start collecting ideas for questions/ queries.

An example query not yet directly related to open science is [Software applications ranked in descending order by the number of writable file formats](https://query.wikidata.org/#%23Software%20applications%20ranked%20in%20descending%20order%20by%20the%20number%20of%20writable%20file%20formats%0A%23defaultView%3ABubbleChart%20%0ASELECT%20%3Fapp%20%3FappLabel%20%28COUNT%28%3Fformat%29%20AS%20%3Fcount%29%0AWHERE%20%7B%0A%20%20%3Fapp%20%28p%3AP31%2Fps%3AP31%2Fwdt%3AP279%29%20wd%3AQ7397%20.%0A%20%20%3Fapp%20wdt%3AP1072%20%3Fformat%20.%0A%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%0A%09%09bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20.%0A%20%20%20%20%0A%7D%0A%20%20%7D%0A%0AGROUP%20BY%20%3Fapp%20%3FappLabel%0AORDER%20BY%20DESC%28%3Fcount%29) .

The [WikiDigi](https://twitter.com/WikiDigi) account on Twitter is tweeting lots of queries like these.

**Comment by bluerasberry** [comment]
@HeidiSeibold I tried to develop these also. Yes you did something clever by making these and yes you got the idea of Wikidata.

It is still easy to find the limitations of Wikidata's data models. I was looking at your "open science movement" item then cross checked it with other social movements, including women's rights movements, black rights movements, LGBT rights movements, etc. It seems that no one has yet modeled how to manage social movements in Wikidata.

Thanks for raising the issue and yes it would be nice at the end to come up with a data visualization. I will try more tomorrow.

**Comment by Daniel-Mietchen** [comment]
Here's a graph builder query that @HeidiSeibold had shared this morning for open science tools indexed in Wikidata: https://angryloki.github.io/wikidata-graph-builder/?property=P31&item=Q52990223&mode=reverse .

Setting up items for these tools and services is one thing, annotating them with useful properties another. To get an idea of the kind of properties that are being used on items that are instances or subclasses of open science tools, queries like this one could be used:

```SPARQL
SELECT DISTINCT ?property ?propertyLabel ?count
WITH {
  SELECT DISTINCT ?property (COUNT(*) AS ?count) WHERE {
    ?item wdt:P31/wdt:P279* wd:Q52990223 ;
    ?p [ ] .
    ?property a wikibase:Property;
                wikibase:claim ?p.
  }
  GROUP BY ?property 
  } AS %results WHERE {
  INCLUDE %results.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
ORDER BY DESC(?count)
LIMIT 100

```

You can [try it out here](https://query.wikidata.org/#SELECT%20DISTINCT%20%3Fproperty%20%3FpropertyLabel%20%3Fcount%0AWITH%20%7B%0A%20%20SELECT%20DISTINCT%20%3Fproperty%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%0A%20%20%20%20%3Fitem%20wdt%3AP31%2Fwdt%3AP279%2a%20wd%3AQ52990223%20%3B%0A%20%20%20%20%3Fp%20%5B%20%5D%20.%0A%20%20%20%20%3Fproperty%20a%20wikibase%3AProperty%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3Aclaim%20%3Fp.%0A%20%20%7D%0A%20%20GROUP%20BY%20%3Fproperty%20%0A%20%20%7D%20AS%20%25results%20WHERE%20%7B%0A%20%20INCLUDE%20%25results.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%7D%0AORDER%20BY%20DESC%28%3Fcount%29%0ALIMIT%20100). 

The more comprehensive the data, the more useful this query should become.

**Comment by bluerasberry** [comment]
I was looking at the Wikidata items for social movements and thinking about how to make sure that anyone who participates in the "open science movement" can tag their work and get due credit for whatever they do, however great or modest.

I was looking at citation structures and considering what kinds of work get less credit. Using academic conference presentations as a start, I wrote out a Wikidata data model for data of events.
https://www.wikidata.org/wiki/Wikidata:WikiProject_Event_Metadata

There is more to be developed but this is a start to collecting information about all sorts of events which broadcast information, and might be recorded and published media, but which are currently uncommon to cite. My goal here was to be able to take in conference programs. 

I am not there but I made some movement on the issue.

**Comment by Daniel-Mietchen** [comment]
I guess @fnielsen would like to take a look at that.

**Comment by Daniel-Mietchen** [comment]
Having thought a bit more about this, I think instead of classifying tools or services as instances or subclasses of open science tool, it might be better to create a catalog of which the tools or services are a part.

**Comment by HeidiSeibold** [comment]
@Daniel-Mietchen I am not sure I understand how to do this. Can you clarify? Has there been any work in this direction so far?

**Comment by Daniel-Mietchen** [comment]
@HeidiSeibold Catalogs are in use in various contexts, from artworks and astronomy to zoology, and there is a dedicated property for that: https://www.wikidata.org/wiki/Property:P972 . There is also 
https://www.wikidata.org/wiki/Property:P360 for lists but I haven't looked much into this.

**Comment by Daniel-Mietchen** [comment]
For some catalogue examples, see https://tools.wmflabs.org/scholia/catalogue/ .

**Comment by Daniel-Mietchen** [comment]
We just had a similar discussion here at the Wikimedia Hackathon on how to index such lists of things, and [ on focus list of Wikimedia project (P5008)](https://www.wikidata.org/wiki/Property:P5008) came up as an additional and possibly better option than catalogues.

**Comment by xolotl** [comment]
Linking this issue to the one focused on open science tool mappings and visualizations #11

**Comment by xolotl** [comment]
This issue was moved to OpenScienceRoadmap/roadmap#7
