### ISSUE TITLE
Brainstorm user stories that touch one or more existing or imagined projects

### ISSUE THREAD

**Issue by dwhly** [OpenScienceRoadmap/mozilla-sprint-2018#8]
[//]: # "=======================
Instructions for posting issues: 
(1) Review what is already there. Perhaps a comment to an existing issue would be more appropriate than opening a new one?  Issues can be a topic idea, a cry for help, an introduction to yourself, a to-do, or a discussion / question about the event itself.
(2) Write your post (below this text blob) using Markdown (as per https://guides.github.com/features/mastering-markdown/ ) or just plain text.
(3) Don't worry about these introductory lines - you can leave or delete them, as they won't display anyway (you can check this via Preview).
(4) Hit the 'Submit new issue' button.
============================"

Based on our personas, and the real world needs of those personas, imagine user stories that characterize new capabilities that do not yet exist either within individual projects, or more importantly *between* two or more projects, that allow people to get things done they wouldn't have been able to before, or to do so more effortlessly or efficiently such that there is a transformative change in capacity or productivity.

These user stories might imply the creation of new standards, or practices,  expanding or normalizing APIs, integrating common systems like identity, authentication, data handling, harmonizing user interface or simply creating new features that did not exist before.

These user stories might be quite narrow, and talk about existing projects, or they might be more broad-- such as, "As a user I need to be able to be signed into as a user across any project I'm working on, so that those projects can leverage a common identity and more easily move data between them."

**Comment by Daniel-Mietchen** [comment]
Depends on the personas (#3).

**Comment by HeidiSeibold** [comment]
This could inform #10

**Comment by nicipfeiffer** [comment]
A starting point... [User Stories for Joint Roadmap of Open Science Tools](https://docs.google.com/document/d/1I3n9sfeYO7U8JbXkk9zmdHL2HjMaPKMFs5BwOtka4zw/edit?usp=sharing)
Please contribute!

**Comment by xolotl** [comment]
This issue was moved to OpenScienceRoadmap/roadmap#8
