### ISSUE TITLE
How can projects join JROST?

### ISSUE THREAD

**Issue by HeidiSeibold** [OpenScienceRoadmap/mozilla-sprint-2018#9]
[//]: # "=======================
Instructions for posting issues: 
(1) Review what is already there. Perhaps a comment to an existing issue would be more appropriate than opening a new one?  Issues can be a topic idea, a cry for help, an introduction to yourself, a to-do, or a discussion / question about the event itself.
(2) Write your post (below this text blob) using Markdown (as per https://guides.github.com/features/mastering-markdown/ ) or just plain text.
(3) Don't worry about these introductory lines - you can leave or delete them, as they won't display anyway (you can check this via Preview).
(4) Hit the 'Submit new issue' button.
============================"
I am a contributor to an open project (https://github.com/openml/OpenML, https://www.openml.org/) and was wondering the following:

- What does it mean for a project to be part of the JROST?
- Where can people add suggestions for projects to join JROST?
- How do members of JROST communicate?
- Which types of projects are of interest for JROST?

I am happy to help put your answers into the contributor guidelines if you'd like.

@openml/core

**Comment by dwhly** [comment]
Hi!

Great questions, let me answer:

"What does it mean for a project to be part of the JROST?"  /  "Which types of projects are of interest for JROST?"

It means that you are a non-profit entity or project, that is building open source tools which have a substantial application within the sciences-- in communication, experimentation, data, collaboration or whatever.  It also means that you're curious and enthusiastic about how you might integrate with other projects in the open ecosystem.  You probably have your own vision how together we can be more than the sum of our parts.

I've looked at OpenML, and you look like exactly the kind of community project we'd love to join.

"Where can people add suggestions for projects to join JROST?"

We probably need a good way to do this, but for now... how about right here?  Thanks for creating the issue!

"How do members of JROST communicate?"

We're sorting that out, the project is brand new.  For now we communicate by email, but we'll be expanding some of those channels.  Here in the sprint.  Feel free to chat with us here, and watch the main page for additional channels we'll be establishing for next week.  https://github.com/OpenScienceRoadmap/mozilla-sprint-2018

We hope you'll join us for the sprint.

**Comment by HeidiSeibold** [comment]
Excellent. I will see if I can make it to the sprint and will also forward the invite to other contributors.

Will there be a meeting at the start of the sprint to organise what people will be working on and to discuss questions this thursday?

**Comment by xolotl** [comment]
@HeidiSeibold apologies for the delay in responding! We are building this airplane while flying ;)

As you may have already seen added to the [project sprint README](https://github.com/OpenScienceRoadmap/mozilla-sprint-2018/blob/master/README.md), we are holding three standup meetings on each sprint day (10–11 May 2018) at the start, middle, and end of each day during EDT (UTC -4). Some are already past, but we welcome your joining future standups! Meanwhile, conversation and coordination continues on GitHub, Twitter, IRC and even in the Zoom chat (sprint communication channels are also in the README).

As for joining JROST formally, we have provided [a process in an adjacent repository](https://github.com/OpenScienceRoadmap/Participants). Please let us know if you have questions or suggestions and we look forward to your participation in the sprint and JROST!

**Comment by HeidiSeibold** [comment]
I think that https://github.com/OpenScienceRoadmap/Participants has solved this issue. Closing now :1st_place_medal:

**Comment by xolotl** [comment]
This issue was moved to OpenScienceRoadmap/jrost#36
